#!/bin/bash
get_gpuvendor () {
if [ $(lspci -k | grep -c "Kernel driver in use: amdgpu") != "0" ]
        then
                gpudriver[0]=amdgpu
                gpuvendor[0]=amd
fi
if [ $(lspci -k | grep -c "Kernel driver in use: radeon") != "0" ]
        then
                gpudriver[1]=radeon
                gpuvendor[0]=amd
fi
if [ $(lspci -k | grep -c "Kernel driver in use: i915") != "0" ]
        then
                gpudriver[2]=i915
                gpuvendor[1]=intel
fi
if [ $(lspci -k | grep -c "Kernel driver in use: nouveau") != "0" ]
        then
                gpudriver[3]=nouveau
                gpuvendor[2]=nvidia
fi
if [ $(lspci -k | grep -c "Kernel driver in use: nvidia") != "0" ]
        then
                gpudriver[4]=nvidia
                gpuvendor[2]=nvidia
fi
if [ $(lspci -k | grep -c "Kernel driver in use: nvidia_drm") != "0" ]
        then
                gpudriver[5]=nvidia_drm
                gpuvendor[2]=nvidia
fi
}
get_gpuvendor
echo ${gpudriver[@]}
echo ${gpuvendor[@]}
exit
